### ISSUE TITLE
How to handle checks which are not pass/fail?

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/repo-audit#38]
So far, every check has a pass or fail result - the licence is either present and correct, or not. But, there are also things we want to have which are informational, e.g. "When was the last commit made, and by whom?"

How should we handle this? One ide would be to have the outcome as the value of the `result` key, like this;

    "last_commit_author" => {
        "result" => "digitalronin"
    }

But, that means we'll have a lot of keys like; `last_commit_author`, `last_commit_timestamp` etc. as opposed to something like;

    "last_commit" => {
        "author" => {
            "name" => "digitalronin",
            "email" => "foo@bar.com"
        },
        "timestamp" => "2017/07/21 11:19:38 BST"
    }

For now, in the `last_commit_check`, I've gone with the latter approach, where that hash is returned as the value of `result`.

Any thoughts?

**Comment by SteveMarshall** [comment]
@digitalronin Is this fixed by #43?

**Comment by digitalronin** [comment]
Sorry, yes. Good catch.

**Comment by digitalronin** [comment]
Fixed by #43
