### ISSUE TITLE
Remove the redundant _check suffix

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/repo-audit#41]
In the yaml file, we have a `checks` section, and all the type values are `xxx_check`

In the code, we call `register_check` with `xxx_check` for each check.

I would say the `_check` suffix is redundant in these cases, and we should get rid of it.

**Comment by zheileman** [comment]
I think I agree with this. It is starting to be very verbose and redundant 💯

**Comment by SteveMarshall** [comment]
Sounds good to me 😎
